 app:
  security:
    whitelist:
      - GET:/v3/api-docs/**
      - GET:/swagger-ui/**
      - GET:/swagger-ui.html
      - GET:/webjars/**
      - POST:/novel/search/**
      - POST:/user/login
      - POST:/user/sendOTP
      - POST:/user/createUser
      - POST:/user/loginByEmail
      - POST:/user/createUserByEmail
      - PUT:/user/forgotPass
      - GET:/user/getId
      - POST:/chapter/getAll
      - GET:/chapter/increaseViewChapter/**
      - GET:/category/getAll
      - GET:/author/getAll
      - GET:/author/**
      - GET:/comment/getAllByChapter/**
      - GET:/comment/getAllByNovel/**
      - GET:/novel/**
      - POST:/novel/search
      - GET:/api/fetch-html
      - POST:/api/tts/speak
      - POST:/api/tts/sub-callback
      - GET:/api/tts/status/**
      - GET:/api/tts/audio/**
      - GET:/ws/**
      - POST:/ws/**
      - OPTIONS:/ws/**
      - GET:/send-private/**
      - POST:/api/payment/create
      - POST:/api/payment/call
      - GET:/api/payment/callback-success/**
      - GET:/api/payment/callback
      - POST:/api/payment/callbackk
      - HEAD:/
    endpoints:
      "[/project/getAll]": "GET: member, manager, admin"

