package com.example.demo.entity;

import jakarta.persistence.*;
import lombok.Data;
import java.io.Serializable;
import java.util.Date;

/**
 * Represents a Refresh Token in the system.
 * Refresh Tokens are used to obtain new Access Tokens without requiring the user
 * to log in again. Each user has only one active Refresh Token at a time.
 * This entity is mapped to the 'refresh_token' table in the database.
 */
@Data
@Entity
@Table(name = "refresh_token")
public class RefreshToken implements Serializable {
    
    /**
     * Unique version identifier for serialization.
     */
    private static final long serialVersionUID = 8058829402313983267L;

    /**
     * Unique ID of the Refresh Token, automatically generated by the database.
     * This is the primary key of the table.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private long idRefreshToken;

    /**
     * Unique token string, usually a UUID.
     * This token must be unique across the entire table and cannot be null.
     */
    @Column(name = "token", length = 255, nullable = false, unique = true)
    private String token;

    /**
     * The expiration date of this Refresh Token.
     * After this date, the token becomes invalid. Cannot be null.
     */
    @Column(name = "expiryDate", nullable = false)
    @Temporal(TemporalType.TIMESTAMP)
    private Date expiryDate;

    /**
     * The user who owns this Refresh Token.
     * This is a One-to-One relationship linking the token to a specific user.
     * The foreign key column 'idUser' in this table references the 'idUser' column in the 'users' table.
     */
    @OneToOne
    @JoinColumn(name = "idUser", referencedColumnName = "idUser")
    private User user;
}
